Lesson3 Homework
DrunkWizard/Qt pull request #1
Opened 2020-03-27 19:03 UTC by DrunkWizard

LoginApp with loader and server request app

2020-04-01 12:43 UTC, mashinapetro requested changes

2020-04-01 12:43 UTC, mashinapetro commented on LoginApp/qml/SignInForm.qml
> +    visible: pageCheck == 0
Зачем это нужно?

2020-04-01 12:43 UTC, mashinapetro commented on LoginApp/qml/SignUpForm.qml
> +    visible: pageCheck == 1
Зачем это нужно?

2020-04-01 14:26 UTC, gleechiro commented on LoginApp/qml/SignInForm.qml
> +    visible: pageCheck == 0
Не нужно, забыл убрать когда выносил в отдельный файл, поправил

2020-04-02 15:37 UTC, mashinapetro commented on LoginApp/qml/SignInForm.qml
> +    visible: pageCheck == 0
Ок!

2020-04-02 15:38 UTC, mashinapetro approved these changes
Все ок!

2020-04-02 17:45 UTC, merged